// 預設內建詞典
const DEFAULT_RULES = [
  // 雙音節 / 常見詞
  { key: "zigong", replacement: "子宮" },
  { key: "jingye", replacement: "精液" },
  { key: "yindao", replacement: "陰道" },
  { key: "rufang", replacement: "乳房" },
  { key: "shejing", replacement: "射精" },
  { key: "guitou", replacement: "龜頭" },
  { key: "yinchun", replacement: "陰唇" },
  { key: "yinjing", replacement: "陰莖" },
  { key: "jiba", replacement: "雞巴" },
  { key: "gaowan", replacement: "睾丸" },
  { key: "chushou", replacement: "觸手" },
  { key: "yinti", replacement: "陰蒂" },
  { key: "yinhe", replacement: "陰核" },
  { key: "tianping", replacement: "舔屏" },
  { key: "zuoai", replacement: "做愛" },
  { key: "luanlun", replacement: "亂倫" },
  { key: "mama", replacement: "媽媽" },
  { key: "baba", replacement: "爸爸" },
  { key: "jiejie", replacement: "姐姐" },
  { key: "gege", replacement: "哥哥" },
  { key: "meimei", replacement: "妹妹" },
  { key: "xiaoxue", replacement: "小穴" },
  { key: "saohuo", replacement: "騷貨" },
  { key: "yuhuo", replacement: "慾火" },
  { key: "guntang", replacement: "滾燙" },
  { key: "shuangma", replacement: "爽嗎" },
  { key: "nongnong", replacement: "濃濃" },
  { key: "taonong", replacement: "套弄" },
  { key: "koujiao", replacement: "口交" },
  { key: "rutou", replacement: "乳頭" },

  // 單音節 / 高頻字與變體
  { key: "gui", replacement: "龜" },
  { key: "chun", replacement: "唇" },
  { key: "tian", replacement: "舔" },
  { key: "cao", replacement: "操" },
  { key: "sao", replacement: "騷" },
  { key: "rou", replacement: "肉" },
  { key: "xi", replacement: "吸" },
  { key: "se", replacement: "色" },
  { key: "xue", replacement: "穴" },
  { key: "bi", replacement: "逼" },
  { key: "ba", replacement: "爸" },
  { key: "cha", replacement: "插" },
  { key: "pgu", replacement: "屁股" },
  { key: "yin", replacement: "淫" },
  { key: "gong", replacement: "宮" },
  { key: "jianian", replacement: "姦" },
  { key: "jian", replacement: "姦" },
];
